/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: opal.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "opal.pb-c.h"
void   pinput_transaction__init
                     (PInputTransaction         *message)
{
  static const PInputTransaction init_value = PINPUT_TRANSACTION__INIT;
  *message = init_value;
}
size_t pinput_transaction__get_packed_size
                     (const PInputTransaction *message)
{
  assert(message->base.descriptor == &pinput_transaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pinput_transaction__pack
                     (const PInputTransaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pinput_transaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pinput_transaction__pack_to_buffer
                     (const PInputTransaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pinput_transaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PInputTransaction *
       pinput_transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PInputTransaction *)
     protobuf_c_message_unpack (&pinput_transaction__descriptor,
                                allocator, len, data);
}
void   pinput_transaction__free_unpacked
                     (PInputTransaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pinput_transaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   poutput_transaction__init
                     (POutputTransaction         *message)
{
  static const POutputTransaction init_value = POUTPUT_TRANSACTION__INIT;
  *message = init_value;
}
size_t poutput_transaction__get_packed_size
                     (const POutputTransaction *message)
{
  assert(message->base.descriptor == &poutput_transaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t poutput_transaction__pack
                     (const POutputTransaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &poutput_transaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t poutput_transaction__pack_to_buffer
                     (const POutputTransaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &poutput_transaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
POutputTransaction *
       poutput_transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (POutputTransaction *)
     protobuf_c_message_unpack (&poutput_transaction__descriptor,
                                allocator, len, data);
}
void   poutput_transaction__free_unpacked
                     (POutputTransaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &poutput_transaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ptransaction__init
                     (PTransaction         *message)
{
  static const PTransaction init_value = PTRANSACTION__INIT;
  *message = init_value;
}
size_t ptransaction__get_packed_size
                     (const PTransaction *message)
{
  assert(message->base.descriptor == &ptransaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ptransaction__pack
                     (const PTransaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ptransaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ptransaction__pack_to_buffer
                     (const PTransaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ptransaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PTransaction *
       ptransaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PTransaction *)
     protobuf_c_message_unpack (&ptransaction__descriptor,
                                allocator, len, data);
}
void   ptransaction__free_unpacked
                     (PTransaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ptransaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   punspent_output_transaction__init
                     (PUnspentOutputTransaction         *message)
{
  static const PUnspentOutputTransaction init_value = PUNSPENT_OUTPUT_TRANSACTION__INIT;
  *message = init_value;
}
size_t punspent_output_transaction__get_packed_size
                     (const PUnspentOutputTransaction *message)
{
  assert(message->base.descriptor == &punspent_output_transaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t punspent_output_transaction__pack
                     (const PUnspentOutputTransaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &punspent_output_transaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t punspent_output_transaction__pack_to_buffer
                     (const PUnspentOutputTransaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &punspent_output_transaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PUnspentOutputTransaction *
       punspent_output_transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PUnspentOutputTransaction *)
     protobuf_c_message_unpack (&punspent_output_transaction__descriptor,
                                allocator, len, data);
}
void   punspent_output_transaction__free_unpacked
                     (PUnspentOutputTransaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &punspent_output_transaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   punspent_transaction__init
                     (PUnspentTransaction         *message)
{
  static const PUnspentTransaction init_value = PUNSPENT_TRANSACTION__INIT;
  *message = init_value;
}
size_t punspent_transaction__get_packed_size
                     (const PUnspentTransaction *message)
{
  assert(message->base.descriptor == &punspent_transaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t punspent_transaction__pack
                     (const PUnspentTransaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &punspent_transaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t punspent_transaction__pack_to_buffer
                     (const PUnspentTransaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &punspent_transaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PUnspentTransaction *
       punspent_transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PUnspentTransaction *)
     protobuf_c_message_unpack (&punspent_transaction__descriptor,
                                allocator, len, data);
}
void   punspent_transaction__free_unpacked
                     (PUnspentTransaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &punspent_transaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pblock__init
                     (PBlock         *message)
{
  static const PBlock init_value = PBLOCK__INIT;
  *message = init_value;
}
size_t pblock__get_packed_size
                     (const PBlock *message)
{
  assert(message->base.descriptor == &pblock__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pblock__pack
                     (const PBlock *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pblock__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pblock__pack_to_buffer
                     (const PBlock *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pblock__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PBlock *
       pblock__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PBlock *)
     protobuf_c_message_unpack (&pblock__descriptor,
                                allocator, len, data);
}
void   pblock__free_unpacked
                     (PBlock *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pblock__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pinput_transaction__field_descriptors[4] =
{
  {
    "transaction",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PInputTransaction, transaction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txout_index",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PInputTransaction, txout_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PInputTransaction, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_key",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PInputTransaction, public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pinput_transaction__field_indices_by_name[] = {
  3,   /* field[3] = public_key */
  2,   /* field[2] = signature */
  0,   /* field[0] = transaction */
  1,   /* field[1] = txout_index */
};
static const ProtobufCIntRange pinput_transaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pinput_transaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PInputTransaction",
  "PInputTransaction",
  "PInputTransaction",
  "",
  sizeof(PInputTransaction),
  4,
  pinput_transaction__field_descriptors,
  pinput_transaction__field_indices_by_name,
  1,  pinput_transaction__number_ranges,
  (ProtobufCMessageInit) pinput_transaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor poutput_transaction__field_descriptors[2] =
{
  {
    "amount",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(POutputTransaction, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(POutputTransaction, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned poutput_transaction__field_indices_by_name[] = {
  1,   /* field[1] = address */
  0,   /* field[0] = amount */
};
static const ProtobufCIntRange poutput_transaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor poutput_transaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "POutputTransaction",
  "POutputTransaction",
  "POutputTransaction",
  "",
  sizeof(POutputTransaction),
  2,
  poutput_transaction__field_descriptors,
  poutput_transaction__field_indices_by_name,
  1,  poutput_transaction__number_ranges,
  (ProtobufCMessageInit) poutput_transaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ptransaction__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PTransaction, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txins",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PTransaction, n_txins),
    offsetof(PTransaction, txins),
    &pinput_transaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txouts",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PTransaction, n_txouts),
    offsetof(PTransaction, txouts),
    &poutput_transaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ptransaction__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = txins */
  2,   /* field[2] = txouts */
};
static const ProtobufCIntRange ptransaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ptransaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PTransaction",
  "PTransaction",
  "PTransaction",
  "",
  sizeof(PTransaction),
  3,
  ptransaction__field_descriptors,
  ptransaction__field_indices_by_name,
  1,  ptransaction__number_ranges,
  (ProtobufCMessageInit) ptransaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor punspent_output_transaction__field_descriptors[3] =
{
  {
    "amount",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PUnspentOutputTransaction, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PUnspentOutputTransaction, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spent",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(PUnspentOutputTransaction, spent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned punspent_output_transaction__field_indices_by_name[] = {
  1,   /* field[1] = address */
  0,   /* field[0] = amount */
  2,   /* field[2] = spent */
};
static const ProtobufCIntRange punspent_output_transaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor punspent_output_transaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PUnspentOutputTransaction",
  "PUnspentOutputTransaction",
  "PUnspentOutputTransaction",
  "",
  sizeof(PUnspentOutputTransaction),
  3,
  punspent_output_transaction__field_descriptors,
  punspent_output_transaction__field_indices_by_name,
  1,  punspent_output_transaction__number_ranges,
  (ProtobufCMessageInit) punspent_output_transaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor punspent_transaction__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PUnspentTransaction, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "coinbase",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(PUnspentTransaction, coinbase),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unspent_txouts",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PUnspentTransaction, n_unspent_txouts),
    offsetof(PUnspentTransaction, unspent_txouts),
    &punspent_output_transaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned punspent_transaction__field_indices_by_name[] = {
  1,   /* field[1] = coinbase */
  0,   /* field[0] = id */
  2,   /* field[2] = unspent_txouts */
};
static const ProtobufCIntRange punspent_transaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor punspent_transaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PUnspentTransaction",
  "PUnspentTransaction",
  "PUnspentTransaction",
  "",
  sizeof(PUnspentTransaction),
  3,
  punspent_transaction__field_descriptors,
  punspent_transaction__field_indices_by_name,
  1,  punspent_transaction__number_ranges,
  (ProtobufCMessageInit) punspent_transaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pblock__field_descriptors[8] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PBlock, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bits",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PBlock, bits),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "previous_hash",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PBlock, previous_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PBlock, hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PBlock, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PBlock, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "merkle_root",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PBlock, merkle_root),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transactions",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PBlock, n_transactions),
    offsetof(PBlock, transactions),
    &ptransaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pblock__field_indices_by_name[] = {
  1,   /* field[1] = bits */
  3,   /* field[3] = hash */
  6,   /* field[6] = merkle_root */
  5,   /* field[5] = nonce */
  2,   /* field[2] = previous_hash */
  4,   /* field[4] = timestamp */
  7,   /* field[7] = transactions */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange pblock__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 9, 7 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor pblock__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PBlock",
  "PBlock",
  "PBlock",
  "",
  sizeof(PBlock),
  8,
  pblock__field_descriptors,
  pblock__field_indices_by_name,
  2,  pblock__number_ranges,
  (ProtobufCMessageInit) pblock__init,
  NULL,NULL,NULL    /* reserved[123] */
};
